os:
  - linux
services:
  - docker
language: java
install: true
jdk:
  - oraclejdk8
sudo: required

script:
  - ./gradlew pushImage -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - chmod +x gradlew
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
notifications:
  email:
    recipients:
      - dwitekw@gmail.com
      - roziu135@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
