os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk8
sudo: false
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
notifications:
  email:
    recipients:
      - dwitekw@gmail.com
      - roziu135@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
